name: Build GTK4 Application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libgtk-4-dev libadwaita-1-dev desktop-file-utils pkg-config gettext meson libpng-dev
      - name: Build application
        run: |
          meson setup builddir
          meson compile -C builddir
      - name: Run tests
        run: |
          meson test -C builddir

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout application code
        uses: actions/checkout@v3

      - name: Install Visual Studio Build Tools
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: 'latest'

      - name: Install Chocolatey packages and Python dependencies
        run: |
          choco install python --yes
          python -m pip install --upgrade pip
          python -m pip install meson ninja

      - name: Clone gvsbuild repository
        run: |
          git clone --depth=1 https://github.com/wingtk/gvsbuild.git

      - name: Build GTK4 dependencies using gvsbuild
        working-directory: gvsbuild
        run: |
          python gvsbuild.py --install gtk4
          python gvsbuild.py --install libadwaita

      - name: Build Application
        run: |
          meson setup builddir --backend=vs
          meson compile -C builddir

      - name: Run Tests
        run: |
          meson test -C builddir
