name: Build GTK4 Application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-4-dev \
            libadwaita-1-dev \
            desktop-file-utils \
            pkg-config \
            gettext \
            meson \
            libpng-dev

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure build
        run: meson setup builddir

      - name: Compile
        run: meson compile -C builddir

      - name: Run tests
        run: meson test -C builddir

  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Explicit version recommended

      - name: Download Gettext
        run: |
          $url = "https://mlocati.github.io/files/gettext-iconv-windows/gettext-0.21.0.zip" # Update to the latest version if needed
          $output = "gettext.zip"
          Invoke-WebRequest -Uri $url -OutFile $output

      - name: Extract Gettext
        run: |
          Expand-Archive -Path gettext.zip -DestinationPath $env:ProgramFiles\gettext
          Remove-Item -Path gettext.zip

      - name: Add Gettext to PATH
        run: |
          $gettextPath = "$env:ProgramFiles\gettext\bin"
          [System.Environment]::SetEnvironmentVariable("Path", $env:Path + ";$gettextPath", [System.EnvironmentVariableTarget]::Machine)

      - name: Install build tools
        run: |
          pip install meson ninja

      - name: Install gvsbuild
        run: |
          pip install git+https://github.com/wingtk/gvsbuild

      - name: Build GTK4 and dependencies
        run: |
          gvsbuild build --enable-gi gtk4 libadwaita libpng

      - name: Set up environment variables
        shell: cmd
        run: |
          echo GTK_INSTALL_PATH=C:\gtk >> %GITHUB_ENV%
          echo PKG_CONFIG_PATH=C:\gtk\lib\pkgconfig >> %GITHUB_ENV%
          echo PATH=C:\gtk\bin;%PATH% >> %GITHUB_ENV%

      - name: Configure build
        run: meson setup builddir

      - name: Compile
        run: meson compile -C builddir

      - name: Run tests
        run: meson test -C builddir
